export default {
  EMPLOYERS_LOAD_ITEMS: 'EMPLOYERS_LOAD_ITEMS',
  EMPLOYERS_ADD: 'EMPLOYERS_ADD',
  EMPLOYERS_DELETE: 'EMPLOYERS_DELETE',
  
  MEMBERS_LOAD_ITEMS: 'MEMBERS_LOAD_ITEMS',
  MEMBERS_ADD: 'MEMBERS_ADD',
  MEMBER_UPDATE: 'MEMBER_UPDATE',
  MEMBER_DELETE: 'MEMBER_DELETE',

  QUESTIONS_LOAD_ITEMS: 'QUESTIONS_LOAD_ITEMS',
  QUESTIONS_ADD: 'QUESTIONS_ADD',
  QUESTIONS_UPDATE: 'QUESTIONS_UPDATE',
  QUESTIONS_REMOVE: 'QUESTION_REMOVE',

  QUESTION_LOAD_ANSWERS: 'QUESTION_LOAD_ANSWERS',
  QUESTION_ADD_ANSWER: 'QUESTION_ADD_ANSWER',
  QUESTION_UPDATE_ANSWER: 'QUESTION_UPDATE_ANSWER',
  QUESTION_REMOVE_ANSWER: 'QUESTION_REMOVE_ANSWER',

  CREDIT_REQUEST_ADD: 'CREDIT_REQUEST_ADD',
  CREDIT_REQUEST_UPDATE: 'CREDIT_REQUEST_UPDATE',
  CREDIT_REQUEST_REMOVE: 'CREDIT_REQUEST_REMOVE'
}
