export default {
  EMPLOYERS_LOAD_ITEMS: 'EMPLOYERS_LOAD_ITEMS',
  EMPLOYERS_ADD: 'EMPLOYERS_ADD',
  EMPLOYERS_DELETE: 'EMPLOYERS_DELETE',
  
  MEMBERS_LOAD_ITEMS: 'MEMBERS_LOAD_ITEMS',
  MEMBERS_ADD: 'MEMBERS_ADD',
  MEMBERS_DELETE: 'MEMBERS_DELETE',

  QUESTIONS_LOAD_ITEMS: 'QUESTIONS_LOAD_ITEMS',
  QUESTIONS_ADD: 'QUESTIONS_ADD',
  QUESTIONS_UPDATE: 'QUESTIONS_UPDATE',
  QUESTIONS_REMOVE: 'QUESTION_REMOVE'
}
